### ISSUE TITLE
[너나들이실][관리자피드백]칭찬 횟수 제한 필요

### ISSUE THREAD

**Issue by wonder13662** [wonder13662/barogo-passport#111]
## 실제 질문
<img width="702" alt="너나들이실_피드백_01" src="https://user-images.githubusercontent.com/15767104/98423106-fcb5ee80-20d0-11eb-9a96-d046c667b6d6.png">

## 관리자 니즈
- 사용자가 하루에 분기별 칭찬을 모두 써버릴 수 있다.

## 요구사항
- 사용자가 하루에 쓸 수 있는 칭찬 갯수를 제한할 필요가 있다
예시) 팀간 3장, 동일인에게 1장 제한 불가능

## TODO
- [ ] 기획 논의 필요(이 방법이 정말 사용자가 원하는 목표인가? 더 나은 방법은 없을까?)
- [ ] 언제까지 해야 할 기능일까?
- [ ] 논의 이후 개별 작업 티켓으로 만들기(기획/UX/개발)

**Comment by wonder13662** [comment]
다영: 공식릴리스까지는 하지 말자
원덕: 회사전체에 칭찬 제한은 제공해보자
주현: 제한하지 말자

결론: 공식릴리스 이후에 논의해보자

**Comment by wonder13662** [comment]
Github 유지는 페이먼트 연동 이후 분리
