### ISSUE TITLE
[너나들이실][행복실][사용자피드백]인원의 팀 이름이 나오지 않음

### ISSUE THREAD

**Issue by wonder13662** [wonder13662/barogo-passport#112]
## 실제 질문
<img width="702" alt="너나들이실_피드백_02" src="https://user-images.githubusercontent.com/15767104/98423732-eb6de180-20d2-11eb-913d-cc4490d73d68.png">
<img width="548" alt="행복실_피드백_04" src="https://user-images.githubusercontent.com/15767104/98430613-187dbc80-20f2-11eb-843d-7a7a965caf47.png">

## 사용자 니즈
팀이름이 나왔으면 좋겠다

## 원인
실제로 받은 데이터에 팀 이름이 없다
<img width="488" alt="Screen Shot 2020-11-07 at 8 25 21 AM" src="https://user-images.githubusercontent.com/15767104/98423781-0f312780-20d3-11eb-9dfa-f6e9bbefb4be.png">

## 논의 사항들
- 사용자에게 그룹명은 보이지 않는다는 안내문구를 제공해야 할까?
- 그룹명은 사용하지 않는데 왜 받는 것일까?(인원이 많은 경우에는 그룹명이 의미가 있다고 보임)
- 인원을 선택할 때 그룹과 팀명을 모두 보여주는 것이 맞지 않을까?
- 그룹명과 팀이 함께 보일 수 있는 UX로 변경이 필요하지 않을까?

## TODO
- [ ] 논의 사항 확인 및 결정
- [ ] 관련 태스크 만들기(기획/UX/개발)
- [ ] 완료 시점 정하기(베타? 또는 공식릴리스?)

**Comment by Godeng** [comment]
팀이 없으면 그룹을 표시하는 방향 ( #112 )
팀과 그룹을 모두 표시하는 방향 둘 다 가능해보이는데요, 일요일에 같이 논의해보시죠!

**Comment by wonder13662** [comment]
다영: 그룹을 노출시켜 주자
1) 팀이 없으면 그룹을 표시
2) 팀이랑 그룹 둘다 표시
원덕: 난 2)번!
주현: 난 1)번!

결론: 1)번 구현 먼저! 그리고 고객 피드백을 받고 결정.

**Comment by Godeng** [comment]
#112 가 1번 안이라 이 이슈는 close하겠습니다!
