### ISSUE TITLE
[너나들이실][사용자피드백]칭찬 최소 입력 글자수 변경 필요

### ISSUE THREAD

**Issue by wonder13662** [wonder13662/barogo-passport#113]
## 실제 질문
<img width="702" alt="너나들이실_피드백_03" src="https://user-images.githubusercontent.com/15767104/98427459-91741880-20e0-11eb-8369-e3017cc476eb.png">

## 사용자 요구사항
글자수 제한 4개 이상 완료 버튼이 생김

## 분석된 요구사항(사용자가 진짜로 원하는 것)
관리자가 글자수 제한을 관리자 설정에서 제어할 수 있도록 해주자

## TODO
- [x] 기획논의 필요(이 방법이 정말 사용자가 원하는 목표인가? 더 나은 방법은 없을까?)
- [x] 언제 사용자가 사용하게 할까?(베타? 릴리스?)
- [x] 관리자 제어 설정 기능으로 추가해야하지 않을까?
- [x] 논의 이후 개별 작업 티켓으로 만들기(기획/UX/개발)

**Comment by wonder13662** [comment]
다영: 글자수 제한은 의미가 없다. 4자 이상 입력해야 입력 가능하다는 가이드는 필요!
원덕: 다영님 의견 동의
주현: 다영님 의견 동의

결론: 칭찬하기 페이지에 가이드가 상시 노출되는 영역을 잡자!

**Comment by Godeng** [comment]
#128 로 진행합니다.
