### ISSUE TITLE
[너나들이실][사용자피드백]웹사이트 초기 접속 시 '비밀번호가 틀렸습니다' 부터 나올때가 있음

### ISSUE THREAD

**Issue by wonder13662** [wonder13662/barogo-passport#115]
## 실제 피드백
<img width="702" alt="너나들이실_피드백_05" src="https://user-images.githubusercontent.com/15767104/98429199-9a68e800-20e8-11eb-8e4a-20926e2de233.png">

## 요구사항
- 웹사이트 초기 접속 시에는 별도의 메시지가 나오지 않아야 함

## TODO 
- [ ] 사용자 요구사항 이외의 추가 작업은 없는지 논의
- [ ] 언제까지 해야할까?(베타 또는 릴리스)
- [ ] 논의 이후 개별 작업 티켓으로 만들기(기획/UX/개발)

**Comment by wonder13662** [comment]
결론: 최초 시점에는 보이지 않도록 수정(개발 이슈)
