### ISSUE TITLE
[너나들이실][관리자피드백]칭찬 통계에서 사람별 칭찬 누적 개수가 나오지 않음

### ISSUE THREAD

**Issue by wonder13662** [wonder13662/barogo-passport#117]
## 실제 피드백
<img width="702" alt="너나들이실_피드백_07" src="https://user-images.githubusercontent.com/15767104/98429819-6ee7fc80-20ec-11eb-85f1-93cf23cf7416.png">

## 관리자 니즈
- 인원별 칭찬 누적갯수로 알 수 있는 것들
   - 분기별 수상자
   - 칭찬 시스템의 활성화 여부

## 논의 사항들
- 이전에 계획했던 칭찬 통계로 위 "관리자 니즈"를 모두 만족하는가?

## TODO 
- [ ] 논의사항 확인 및 결정
- [ ] 관련 태스트 만들기 또는 연동(기획/UX/개발)
- [ ] 완료시점 정하기(베타 또는 릴리스)

**Comment by wonder13662** [comment]
빨리 하자!
