### ISSUE TITLE
[행복실][사용자피드백]내가 받은 칭찬 / 내가 받은 스티커 용어의 이해가 명확하지 않음

### ISSUE THREAD

**Issue by wonder13662** [wonder13662/barogo-passport#120]
## 실제 피드백
<img width="548" alt="행복실_피드백_03" src="https://user-images.githubusercontent.com/15767104/98430498-1a934b80-20f1-11eb-8dea-1e05d05de0d2.png">

## 사용자 니즈
칭찬의 의미, 스티커의 의미가 더 명확해야 한다

## 논의 사항들
- 스티커, 칭찬에 대한 설명을 커스터마이징을 할 수 있도록 해야 하지 않을까? 
- 관리자 세팅 페이지에서 스티커 세팅, 칭찬 세팅을 할 수 있도록 해야 하지 않을까?

## TODO
- [ ] 논의 사항 확인 및 결정 
- [ ] 관련 태스크 만들기(기획/UX/개발)
- [ ] 완료시점 정하기(베타 또는 릴리스)

**Comment by Godeng** [comment]
지적해주신 점을 저는 이렇게 이해했어요!
내가 받은 칭찬 / 내가 받은 스티커는 칭찬 화면 왼쪽에 있는 항목들인것같은데, 그 항목이 무슨뜻인지가 이해가 안된다..

그래서 내가 받은 칭찬 / 내가 받은 스티커의 용어 개선을 해보는건 어떨까요?
ex)
 3번 칭찬받았어요! (스티커+5)
 5번 칭찬했어요.

**Comment by wonder13662** [comment]
다영: 스코어보드의 텍스트가 명확하지 않음. 
칭찬과 스티커를 연결해서 정보를 제공하자.
주현: 다영님 의견 동의
원덕: 다영님 의견 동의

결론: 칭찬과 스티커를 연결해서 정보를 제공하자. 디자인 시안도 다시 잡아봐야 할 것 같다.

**Comment by Godeng** [comment]
![image](https://user-images.githubusercontent.com/46670402/98466712-a651c880-2214-11eb-96ca-973530139ae7.png)
